install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,9 +12,24 @@ function yes_or_no {
 
 echo "[0/4] Installing development limix version"
 
-which conda &>/dev/null
+command -v python >/dev/null 2>&1
+if [ $? -eq 1 ]
+then
+    echo >&2 "python command has not been found. Aborting."
+    exit 1
+fi
 
-if [ $? == 0 ]
+command -v pip >/dev/null 2>&1
+if [ $? -eq 1 ]
+then
+    echo >&2 "pip command has not been found. Aborting."
+    exit 1
+fi
+
+
+USE_CONDA="no"
+command -v conda >/dev/null 2>&1
+if [ $? -eq 0 ]
 then
     echo "Looks like you have conda package manager."
     msg="Shall we use it to install the C libraries? (Recommended.)"
@@ -31,6 +46,16 @@ function cleanup
 }
 
 trap cleanup EXIT
+
+if [[ $USE_CONDA == "no" ]]
+then
+    command -v cmake >/dev/null 2>&1
+    if [ $? -eq 1 ]
+    then
+        echo >&2 "cmake command has not been found. Aborting."
+        exit 1
+    fi
+fi
 
 function silent_run
 {
@@ -61,7 +86,7 @@ function failed
 GIT_URL=https://github.com/limix/limix.git
 GIT_FOLDER="$tmpdir/limix"
 
-echo -n "[1/5] Cloning repository... "
+echo -n "[1/4] Cloning repository... "
 silent_run git clone -b develop $GIT_URL $GIT_FOLDER
 cd $GIT_FOLDER
 [ $? == 0 ] && echo "done." || failed
